name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x, 20.x, 22.x]

    env:
      HEADLESS: true

    steps:
    - name: Prepare git
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install Node.js dependencies
      run: npm ci

    - name: Code linter
      run: npm run lint

    - name: Build package and setup code coverage reporting
      run: npm run pretest

    - name: Browser tests
      run: npm run test:browser

    - name: Node.js tests
      run: npm run test:node

    - name: Code coverage
      run: npm run posttest
